"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-25 08:11:34.359448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('input_summary', sa.JSON(), nullable=True),
    sa.Column('output_summary', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_scope'), ['scope'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('result_entity_type', sa.String(length=50), nullable=True),
    sa.Column('result_entity_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key', name='uq_idempotency_scope_key')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_records_scope'), ['scope'], unique=False)

    op.create_table('niches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('saturation_score', sa.Float(), nullable=True),
    sa.Column('avg_cpm_est', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('niches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_niches_name'), ['name'], unique=True)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whop_campaign_id', sa.String(length=200), nullable=True),
    sa.Column('brand_name', sa.String(length=200), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=True),
    sa.Column('payout_model', sa.String(length=100), nullable=True),
    sa.Column('cpm_rate', sa.Float(), nullable=True),
    sa.Column('budget_cap', sa.Float(), nullable=True),
    sa.Column('budget_remaining_est', sa.Float(), nullable=True),
    sa.Column('rules_text', sa.Text(), nullable=True),
    sa.Column('rules_json', sa.JSON(), nullable=True),
    sa.Column('ai_content_allowed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'APPROVED', 'REJECTED', 'EXPIRED', name='campaignstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_whop_campaign_id'), ['whop_campaign_id'], unique=True)

    op.create_table('hook_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=True),
    sa.Column('hook_text', sa.Text(), nullable=False),
    sa.Column('hook_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.Enum('INTERNAL', 'COMPETITOR_OBSERVED', name='hooksource', native_enum=False, length=32), nullable=False),
    sa.Column('best_viral_score', sa.Float(), nullable=True),
    sa.Column('retention_at_3s', sa.Float(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hook_library', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hook_library_niche_id'), ['niche_id'], unique=False)

    op.create_table('learning_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=True),
    sa.Column('pattern_type', sa.Enum('HOOK', 'STRUCTURE', 'NICHE', 'TIMING', name='patterntype', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pattern_template_id', sa.String(length=100), nullable=True),
    sa.Column('confidence_tier', sa.Enum('CANDIDATE', 'CONFIRMED', 'RETIRED', name='patternconfidencetier', native_enum=False, length=32), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('supporting_video_ids', sa.JSON(), nullable=False),
    sa.Column('outcome_tag', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_patterns_niche_id'), ['niche_id'], unique=False)

    op.create_table('campaign_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('expected_roi_low', sa.Float(), nullable=True),
    sa.Column('expected_roi_median', sa.Float(), nullable=True),
    sa.Column('expected_roi_high', sa.Float(), nullable=True),
    sa.Column('difficulty_score', sa.Float(), nullable=True),
    sa.Column('competition_level', sa.Float(), nullable=True),
    sa.Column('niche_fit_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('breakdown_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_scores_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('content_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('concept_summary', sa.Text(), nullable=False),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_ideas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_ideas_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('research_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('raw_input_notes', sa.Text(), nullable=True),
    sa.Column('brief_text', sa.Text(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_briefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_briefs_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('variant_label', sa.String(length=50), nullable=False),
    sa.Column('experiment_group', sa.String(length=50), nullable=True),
    sa.Column('hook_text', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('cta_text', sa.Text(), nullable=True),
    sa.Column('target_duration_s', sa.Integer(), nullable=True),
    sa.Column('generation_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scripts_idea_id'), ['idea_id'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_RENDER', 'RENDERED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'REVISION_REQUESTED', 'PUBLISHED', 'RENDER_FAILED', name='videostatus', native_enum=False, length=32), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('render_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('render_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('render_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('asset_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('caption_style', sa.String(length=100), nullable=True),
    sa.Column('contains_ai_voice', sa.Boolean(), nullable=False),
    sa.Column('contains_ai_visual', sa.Boolean(), nullable=False),
    sa.Column('qc_status', sa.String(length=50), nullable=True),
    sa.Column('qc_notes', sa.Text(), nullable=True),
    sa.Column('tts_agent_run_id', sa.Integer(), nullable=True),
    sa.Column('render_agent_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['render_agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.ForeignKeyConstraint(['tts_agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_script_id'), ['script_id'], unique=False)

    op.create_table('cost_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_ledger_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_ledger_video_id'), ['video_id'], unique=False)

    op.create_table('metrics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('avg_watch_time_s', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('completion_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rewatch_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metrics_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_snapshots_video_id'), ['video_id'], unique=False)

    op.create_table('quality_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('originality_score', sa.Float(), nullable=True),
    sa.Column('retention_prediction_score', sa.Float(), nullable=True),
    sa.Column('policy_risk_score', sa.Float(), nullable=True),
    sa.Column('monetization_probability_score', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_scores_video_id'), ['video_id'], unique=True)

    op.create_table('revenue_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_views', sa.Integer(), nullable=True),
    sa.Column('approved_views', sa.Integer(), nullable=True),
    sa.Column('payout_realized', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payout_pending', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revenue_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revenue_snapshots_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revenue_snapshots_video_id'), ['video_id'], unique=False)

    op.create_table('review_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'REVISION_REQUESTED', name='reviewdecisiontype', native_enum=False, length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_decisions_video_id'), ['video_id'], unique=False)

    op.create_table('viral_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metrics_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('breakdown_json', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['metrics_snapshot_id'], ['metrics_snapshots.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('viral_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_viral_scores_metrics_snapshot_id'), ['metrics_snapshot_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_viral_scores_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viral_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viral_scores_video_id'))
        batch_op.drop_index(batch_op.f('ix_viral_scores_metrics_snapshot_id'))

    op.drop_table('viral_scores')
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_decisions_video_id'))

    op.drop_table('review_decisions')
    with op.batch_alter_table('revenue_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revenue_snapshots_video_id'))
        batch_op.drop_index(batch_op.f('ix_revenue_snapshots_campaign_id'))

    op.drop_table('revenue_snapshots')
    with op.batch_alter_table('quality_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_scores_video_id'))

    op.drop_table('quality_scores')
    with op.batch_alter_table('metrics_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_snapshots_video_id'))

    op.drop_table('metrics_snapshots')
    with op.batch_alter_table('cost_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_ledger_video_id'))
        batch_op.drop_index(batch_op.f('ix_cost_ledger_campaign_id'))

    op.drop_table('cost_ledger')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_script_id'))

    op.drop_table('videos')
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scripts_idea_id'))

    op.drop_table('scripts')
    with op.batch_alter_table('research_briefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_briefs_campaign_id'))

    op.drop_table('research_briefs')
    with op.batch_alter_table('content_ideas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_ideas_campaign_id'))

    op.drop_table('content_ideas')
    with op.batch_alter_table('campaign_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_scores_campaign_id'))

    op.drop_table('campaign_scores')
    with op.batch_alter_table('learning_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_patterns_niche_id'))

    op.drop_table('learning_patterns')
    with op.batch_alter_table('hook_library', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hook_library_niche_id'))

    op.drop_table('hook_library')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_whop_campaign_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('niches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_niches_name'))

    op.drop_table('niches')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_scope'))
        batch_op.drop_index(batch_op.f('ix_idempotency_records_key'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_scope'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_name'))

    op.drop_table('agent_runs')
    # ### end Alembic commands ###
