"""cost control layer (Phase 2 M1)

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-25 17:44:36.198879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('LOG', 'SLACK', 'EMAIL', name='notificationchannel', native_enum=False, length=16), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='notificationseverity', native_enum=False, length=16), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_quota_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('quota_period', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('units_used', sa.Integer(), nullable=False),
    sa.Column('units_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'quota_period', 'period_start', name='uq_provider_quota_period')
    )
    with op.batch_alter_table('provider_quota_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_quota_usage_provider'), ['provider'], unique=False)

    op.create_table('budget_ceilings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('SYSTEM', 'NICHE', name='budgetscope', native_enum=False, length=16), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=True),
    sa.Column('monthly_limit_usd', sa.Float(), nullable=False),
    sa.Column('last_alert_threshold_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_ceilings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_ceilings_niche_id'), ['niche_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_ceilings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_ceilings_niche_id'))

    op.drop_table('budget_ceilings')
    with op.batch_alter_table('provider_quota_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_quota_usage_provider'))

    op.drop_table('provider_quota_usage')
    op.drop_table('notifications_log')
    # ### end Alembic commands ###
