"""creator account management (Phase 2 M3)

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-25 18:01:14.392214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owned_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('TIKTOK', 'YOUTUBE', 'INSTAGRAM', name='accountplatform', native_enum=False, length=16), nullable=False),
    sa.Column('handle', sa.String(length=200), nullable=False),
    sa.Column('encrypted_oauth_token', sa.Text(), nullable=True),
    sa.Column('niche_focus_id', sa.Integer(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('health_tier', sa.Enum('HEALTHY', 'WATCH', 'AT_RISK', 'RESTRICTED', name='accounthealthtier', native_enum=False, length=16), nullable=False),
    sa.Column('warmup_status', sa.Enum('WARMING', 'ACTIVE', name='accountwarmupstatus', native_enum=False, length=16), nullable=False),
    sa.Column('daily_post_cap', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'SUSPENDED', name='accountstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['niche_focus_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'handle', name='uq_owned_accounts_platform_handle')
    )
    with op.batch_alter_table('owned_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owned_accounts_health_tier'), ['health_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_owned_accounts_niche_focus_id'), ['niche_focus_id'], unique=False)

    op.create_table('account_health_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('tier', sa.Enum('HEALTHY', 'WATCH', 'AT_RISK', 'RESTRICTED', name='accounthealthtier', native_enum=False, length=16), nullable=False),
    sa.Column('posting_cadence_used', sa.Integer(), nullable=False),
    sa.Column('cap_utilization_pct', sa.Float(), nullable=False),
    sa.Column('engagement_trend', sa.Float(), nullable=False),
    sa.Column('strikes_count', sa.Integer(), nullable=False),
    sa.Column('api_error_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['owned_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_health_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_health_snapshots_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_health_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_health_snapshots_account_id'))

    op.drop_table('account_health_snapshots')
    with op.batch_alter_table('owned_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owned_accounts_niche_focus_id'))
        batch_op.drop_index(batch_op.f('ix_owned_accounts_health_tier'))

    op.drop_table('owned_accounts')
    # ### end Alembic commands ###
