"""publishing agent (Phase 2 M4)

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-25 22:17:15.298079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('TIKTOK', 'YOUTUBE', 'INSTAGRAM', name='accountplatform', native_enum=False, length=16), nullable=False),
    sa.Column('external_post_id', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'PUBLISHED', 'FAILED', 'REMOVED', name='publicationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('publish_agent_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['owned_accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['publish_agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publications_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_video_id'))
        batch_op.drop_index(batch_op.f('ix_publications_status'))
        batch_op.drop_index(batch_op.f('ix_publications_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_publications_account_id'))

    op.drop_table('publications')
    # ### end Alembic commands ###
