"""experimentation engine (Phase 2 M6)

Revision ID: 0007
Revises: 0006
Create Date: 2026-07-25 22:28:57.845630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('axis', sa.Enum('HOOK', 'NICHE', 'LENGTH', 'POSTING_TIME', name='experimentaxis', native_enum=False, length=16), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'CONCLUDED', 'INCONCLUSIVE', name='experimentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('min_sample_size', sa.Integer(), nullable=False),
    sa.Column('significance_threshold', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('concluded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.Enum('HOOK', 'NICHE', 'LENGTH_BUCKET', 'POSTING_TIME_BUCKET', name='experimentsubjecttype', native_enum=False, length=20), nullable=False),
    sa.Column('subject_key', sa.String(length=200), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('avg_viral_score', sa.Float(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_by', sa.String(length=100), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiment_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_results_experiment_id'), ['experiment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiment_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_results_experiment_id'))

    op.drop_table('experiment_results')
    op.drop_table('experiments')
    # ### end Alembic commands ###
