"""database optimization (Production Hardening Sprint H5)

Adds the hot-path indexes the production readiness review's D1 finding
flagged as missing (cost_ledger.recorded_at, filtered on every
enforce_budget call; experiment_results.is_winner, filtered by the default
GET /experimentation/recommendations path), and replaces publications'
three separate single-column indexes (account_id, status — published_at
was never indexed at all) with one composite index matching the actual
query shape in publishing_service.py's cadence-cap check. Also closes D4,
dropping idempotency_records' redundant standalone scope/key indexes,
superseded by the existing (scope, key) unique constraint's own composite
index.

Revision ID: 0008
Revises: 0007
Create Date: 2026-07-26 03:22:56.457904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_ledger_recorded_at'), ['recorded_at'], unique=False)

    with op.batch_alter_table('experiment_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_results_is_winner'), ['is_winner'], unique=False)

    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_key'))
        batch_op.drop_index(batch_op.f('ix_idempotency_records_scope'))

    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_account_id'))
        batch_op.drop_index(batch_op.f('ix_publications_status'))
        batch_op.create_index('ix_publications_account_status_published', ['account_id', 'status', 'published_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index('ix_publications_account_status_published')
        batch_op.create_index(batch_op.f('ix_publications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_records_key'), ['key'], unique=False)

    with op.batch_alter_table('experiment_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_results_is_winner'))

    with op.batch_alter_table('cost_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_ledger_recorded_at'))

    # ### end Alembic commands ###
